#!/bin/bash
#
# Title:      PlexGuide (Reference Title File)
# Author(s):  Admin9705
# URL:        https://plexguide.com - http://github.plexguide.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: true
  tasks:

    # PULLS PROVIDER INFO ######################################################
    - name: 'Including cron job'
      include_tasks: '/opt/traefik/provider.yml'

    # MAIN #####################################################################
    - name: Deploy Traefik
      docker_container:
        name: traefik
        image: traefik:1.7
        pull: yes
        published_ports:
          - "443:443"
          - "80:80"
        env:
          PUID: 1000
          PGID: 1000
          PROVIDER: namecheap
          NAMECHEAP_API_USER: "{{part1.stdout}}"
          NAMECHEAP_API_KEY: "{{part2.stdout}}"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
          - /etc/localtime:/etc/localtime:ro
          - /opt/appdata/traefik/traefik.toml:/etc/traefik/traefik.toml:ro
          - /opt/appdata/traefik/acme:/etc/traefik/acme
        restart_policy: unless-stopped
        state: started
        networks:
          - name: plexguide
            aliases:
              - traefik
